# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-LibUniverIt_Driver
version:      0.11
version_from: lib/WWW/Scraper/ISBN/LibUniverIt.pm
installdirs:  site
requires:
    HTML::Entities:                1.32
    LWP::UserAgent:                2
    WWW::Scraper::ISBN:            0.25
    WWW::Scraper::ISBN::Driver:    0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
